### ISSUE TITLE
[filesystems] Overfull hboxes in Filesystem subclause

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1540] opened 2017-03-15 03:08 UTC
There are lots, but these are some of the worst.

[path.construct] p7:
![construct](https://cloud.githubusercontent.com/assets/1254480/23931678/385425a4-092b-11e7-84df-cf5c19723129.png)

[path.generic.obs] p2:
![generic](https://cloud.githubusercontent.com/assets/1254480/23931652/fff4009e-092a-11e7-961e-b22549bab02a.png)

[filesystem_error.members] p7:
![error](https://cloud.githubusercontent.com/assets/1254480/23931742/96aaaa2e-092b-11e7-8076-d54fe48e8a67.png)

[fs.op.create_directory] p5:
![createdir](https://cloud.githubusercontent.com/assets/1254480/23931787/f91ca0ea-092b-11e7-8f4f-d90729ad7d0b.png)

**Comment by jwakely** [comment] 2017-03-15 03:13
[fs.op.copy] and [fs.op.copy] are bad too.

**Comment by jwakely** [comment] 2017-03-15 03:18
One in [fs.op.absolute] can be fixed by simply removing the paragraph break before "For Windows-based ..."

**Comment by jensmaurer** [comment] 2017-03-15 16:51
We should probably fix this for C++17 once the motions have been merged.

**Comment by burblebee** [comment] 2017-03-15 19:16
Can someone please document on the wiki how to find and fix these issues?

**Comment by jwakely** [comment] 2017-03-15 19:47
Added to https://github.com/cplusplus/draft/wiki/Q-&-A - improvements welcome.

**Comment by burblebee** [comment] 2017-03-15 20:39
@jwakely Thank you!!  :)

**Comment by tkoeppe** [comment] 2017-03-15 22:40
Duplicate of #693?

**Comment by zygoloid** [comment] 2017-03-16 01:30
I already have a branch ready to fix all the overfull hboxes.

**Closed** 2017-03-16 02:05 UTC

**Comment by jensmaurer** [comment] 2017-03-20 07:50
Richard has fixed all overfull hboxes with commit 89260fb12a98e5791e2ecaa83a8b3b9d9fed6844.
