### ISSUE TITLE
Whitespace in index

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#664] opened 2016-03-27 18:34 UTC
Sometimes the normal whitespace is used inside `\indextext{}`, sometimes the special character `~` is used. E.g. [class.tex line 119](https://github.com/cplusplus/draft/blob/master/source/classes.tex#L119):

```
\indextext{access control!\idxcode{union} default member}%
```

[class.tex line 1363](https://github.com/cplusplus/draft/blob/master/source/classes.tex#L1363):

```
\indextext{access~control!anonymous \tcode{union}}%
```

This results in two index entries named "access control" appearing in the general index.

**Comment by Eelis** [comment] 2016-11-20 20:05
This particular one was fixed by https://github.com/cplusplus/draft/pull/942

**Comment by tkoeppe** [comment] 2016-11-20 20:21
Duplicate of #1064.

**Closed by tkoeppe** 2016-11-20 20:21 UTC
