### ISSUE TITLE
The reference of a conversion function(template) with a deduced return type

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4671] opened 2021-06-09 06:36 UTC
In N4861, the relevant rule [temp.mem#5](https://timsong-cpp.github.io/cppwp/n4861/temp.mem#5) is: 
> A specialization of a conversion function template is referenced in the same way as a non-template conversion function that converts to the same type.     

After P1787, the above normative rule is radically changed to be a [note](https://eel.is/c++draft/temp.mem#5)    

> [Note 1: A specialization of a conversion function template is referenced in the same way as a non-template conversion function that converts to the same type ([class.conv.fct]).  

There's no normative rule based on to interpret why we should use `a.operator int*();` to refer to the specialization. I also feel that this issue is similar with [How to explicitly call a conversion function whose conversion-type-id contains a placeholder specifier](https://stackoverflow.com/q/66485833/11796722) that I have posted it to wmm@edg.com, which has became the issue 2493 that will be published on http://open-std.org/jtc1/sc22/wg21/

**Comment by jensmaurer** [comment] 2021-08-13 05:32
Duplicate of #4811 CWG2493.

**Closed by jensmaurer** 2021-08-13 05:32 UTC

**Comment by xmh0511** [comment] 2021-08-13 06:03
@jensmaurer It is a bit similar to #4811 but not completely. One is template function, the other is a function with place-holder return type.

**Comment by jensmaurer** [comment] 2021-08-13 06:17
Agreed.

The rationale for the conversion function template case is that the deduction that needs to happen here is part of name lookup. [class.member.lookup] p7

**Comment by xmh0511** [comment] 2021-08-13 06:25
@jensmaurer  So, I think it should be an individual issue that should proceed. After all, the deduction of a conversion function template occurs as a part of name lookup and that is deduced with the actual argument. Instead, the conversion function with the place-holder is directly deduced from its return statement.

**Comment by jensmaurer** [comment] 2021-08-13 07:04
I'm saying the normative rule for the template case is in [class.member.lookup] p7. If you feel that's insufficient, please give more details. And fix the heading if this particular issue is not about deduced return types, but just about conversion function templates.

**Comment by xmh0511** [comment] 2021-08-13 07:20
@jensmaurer  After further consideration, you're right. [class.member.lookup] p7 has clarified this.
