### ISSUE TITLE
CI failing due to "disk quota exceeded"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1853] opened 2017-11-27 18:07 UTC
Example: https://travis-ci.org/cplusplus/draft/jobs/307613875

@godbyk Any thoughts about what we should do about this?

**Comment by tkoeppe** [comment] 2017-11-27 18:09
Eek. Is the quota accumulated over time?

**Comment by godbyk** [comment] 2017-11-27 18:35
I haven't encountered that error before. It's nothing to do with our stuff specifically. The error is occurring before it even gets to the point of running our `.travis-ci.yml` scripts.

It appears that there was [an incident](https://www.traviscistatus.com/incidents/5pc6vqmh9wnh) yesterday that may be the cause. They say it should be resolved now. If you visit the [build page](https://travis-ci.org/cplusplus/draft/builds/307613873) you should be able to click the 'rerun build' (counter-clockwise arrow) button at the top right to have it try that job again.

If it continues to be a problem, please let me know and I'll investigate it further.

**Comment by tkoeppe** [comment] 2017-11-27 19:00
This seems like a momentary glitch, let's close this for now until further repeat occurrences.

**Closed by tkoeppe** 2017-11-27 19:00 UTC
