### ISSUE TITLE
 [2018-06 LWG Motion 14] P0788R3 Standard library specification in a concepts and contracts world

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2132] opened 2018-06-09 08:44 UTC

**Comment by W-E-Brown** [comment] 2018-06-09 10:41
I have LaTeX markup corresponding to the wording from my paper.  If it might be helpful to have, please let me know to whom I should email it.


> On Jun 9, 2018, at 10:44 AM, Jens Maurer <notifications@github.com> wrote nothing:

**Comment by jensmaurer** [comment] 2018-06-09 10:51
@W-E-Brown, please attach the LaTeX source as a file to this issue. Thanks.

**Comment by jwakely** [comment] 2018-06-11 13:36
Or email it to me and I'll assign myself to do the work.

**Comment by jwakely** [comment] 2018-06-11 22:05
Editorial issue noticed:

[res.on.required] p1 is altered to say "_Requires:_ element" instead of "_Requires: paragraph" but still says "_Throws:_ paragraph".

**Comment by jwakely** [comment] 2018-06-11 22:28
An added example in [structure.specification] says "an implementation-defined attribute such as `[[expects]]`"

Implementation-defined attributes should be scoped.

**Comment by jwakely** [comment] 2018-06-11 22:34
The last sentence of [structure.specifications] p4 still refers to a _Postconditions:_ element, which should be _Ensures:_.

**Comment by W-E-Brown** [comment] 2018-06-11 22:38
> On Jun 11, 2018, at 5:05 PM, Jonathan Wakely <notifications@github.com> wrote:
> 
> Editorial issue noticed:
> 
> [res.on.required] p1 is altered to say "Requires: element" instead of "_Requires: paragraph" but still says "Throws: paragraph".

Sigh.  Yeah, I missed that one, and likewise another in the footnote attached to [structure.specifications]/3.  Mea culpa.

Please do fix these editorially; I hope it's clear that consistently changing "paragraph" to "element" was intended in these subclauses.

Thanks for catching this.

**Comment by W-E-Brown** [comment] 2018-06-11 22:42
> On Jun 11, 2018, at 5:28 PM, Jonathan Wakely <notifications@github.com> wrote:
> 
> An added example in [structure.specification] says "an implementation-defined attribute such as [[expects]]"
> 
> Implementation-defined attributes should be scoped.

Yes, but with the adoption of the contracts proposal, this example attribute is no longer implementation-defined.  I recommend editorially striking "implementation-defined" from the example.

**Comment by jwakely** [comment] 2018-06-11 22:44
All the issues mentioned above have been fixed on the branch (as separate commits). Thanks for the quick responses, @W-E-Brown

**Comment by jwakely** [comment] 2018-06-11 23:06
Oops, the branch I pushed is missing all the renaming of _Postconditions:_ to _Ensures:_, I forgot to merge that in before pushing it.

**Comment by jwakely** [comment] 2018-06-11 23:13
Instead of changing every `\postconditions` to `\ensures` throughout the library clauses, the commit I've pushed to the branch simply redefines `\postconditions`:

    \newcommand{\postconditions}{\ensures}

**Comment by timsong-cpp** [comment] 2018-06-12 02:59
So "equivalent to" doesn't propagate _Requires:_ anymore? It seems like we should keep _Requires:_ in [structure.specifications]/4 until we actually get rid of the element.

**Comment by jensmaurer** [comment] 2018-06-12 06:42
@jwakely: If we do get rid of an element, we should also do a global search/replace in the LaTeX, otherwise editoris will be confused for generations to come. We can do that after the mailing, though.

**Comment by jwakely** [comment] 2018-06-12 19:53
@timsong-cpp good point.

@jensmaurer yes, I think we should wait until all the motions are merged, then replace all `\postconditions` with `\ensures` (if we do it now we might get some creeping back in from merged motions).

**Closed** 2018-06-21 02:08 UTC
