### ISSUE TITLE
[ranges.syn] Should the *namespace-alias* `std::views` be `// freestanding`?

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5724] opened 2022-08-12 16:07 UTC
Related comments: https://github.com/cplusplus/draft/pull/5713#discussion_r939550414 https://github.com/cplusplus/draft/pull/5713#discussion_r939686289

https://wg21.link/p1642r11 defines
> A _freestanding entity_ is a declaration or macro definition that is present in a freestanding implementation and a hosted implementation.
> [...]
>  In a header synopsis, entities followed with a comment that includes _freestanding_ are freestanding entities.

Notably, a freestanding entity is not an entity:
> [3](https://eel.is/c++draft/basic.pre#3) [#](http://github.com/Eelis/draft/tree/f8a8938fca3df9775504cdd4d224b1f3987d1e5b/source/basic.tex#L29) An [entity](https://eel.is/c++draft/basic.pre#def:entity) is a value, object, reference, structured binding, function, enumerator, type, class member, bit-field, template, template specialization, namespace, or pack[.](https://eel.is/c++draft/basic.pre#3.sentence-1)

The paper has the following instructions:
> Change in [[ranges.syn]](https://wg21.link/ranges.syn)
Drafting note:
[...]
Instructions to the editor:
Please append a `// freestanding` comment to every entity in `<ranges>` except for the following entities:
> ```
>     basic_istream_view
>     istream_view
>     wistream_view
>     views::istream
> ```

The paper instructs to append `// freestanding` to entities in `<ranges>`, which excludes the _namespace-alias_  `std::views` by definition.

I commented:
> I suppose this begs the question, do freestanding implementations have to use `std::ranges::views` rather than `std::views`?
> -- https://github.com/cplusplus/draft/pull/5713#discussion_r940298499

Currently, by my fault, https://github.com/cplusplus/draft/pull/5713 does append `// freestanding` to `std::views`, but that currently has no effects since `std::views` is not an entity.

**Comment by CaseyCarter** [comment] 2022-08-12 18:09
The root cause here seems to be that [freestanding.entity]/3 uses "entities":

> In a header synopsis, entities followed with a comment that includes _freestanding_ are freestanding entities.

where it should instead say "declarations and macro definitions":

> In a header synopsis, declarations and macro definitions followed with a comment that includes _freestanding_ are freestanding entities.

As is fairly obvious from the following example that applies such a comment to a macro definition, which is not an entity.

**Comment by JohelEGP** [comment] 2022-08-13 21:32
> I think we need an LWG issue to normatively fix [freestanding.entity]/3.

It's also necessary to clarify whether the paper's instructions to the editor that mention "every entity" actually meant "all declarations and macro definitions". `std::views` should be a freestanding entity.

**Comment by JohelEGP** [comment] 2022-08-14 21:45
> > I think we need an LWG issue to normatively fix [freestanding.entity]/3.
> 
> It's also necessary to clarify whether the paper's instructions to the editor that mention "every entity" actually meant "all declarations and macro definitions". `std::views` should be a freestanding entity.

That'd also help clarify https://github.com/cplusplus/draft/pull/5713#discussion_r939710891. As per the literal instructions, class members of `allocator_arg_t` and more are appended `// freestanding`, but not those of `allocation_result`.

**Comment by tkoeppe** [comment] 2022-08-20 22:18
@ben-craig: would you care to file an LWG issue for this?

**Comment by jwakely** [comment] 2022-08-23 10:12
This will be LWG 3753.

**Comment by tkoeppe** [comment] 2022-08-23 10:54
Thank you! I will close this editorial issue then, and see you in the next meeting's motions :-)

**Closed by tkoeppe** 2022-08-23 10:54 UTC

**Comment by JohelEGP** [comment] 2022-08-23 14:18
Should this get a LWG label for consistency with issues with a CWG label being closed after a corresponding CWG issue is created?

**Comment by tkoeppe** [comment] 2022-08-23 14:24
Since it's already closed, I really don't care, nor can I think of anyone who would. Do you?

**Comment by JohelEGP** [comment] 2022-08-23 14:33
No, if there's no value to it.

**Comment by JohelEGP** [comment] 2022-08-23 14:38
> > > I think we need an LWG issue to normatively fix [freestanding.entity]/3.
> > 
> > 
> > It's also necessary to clarify whether the paper's instructions to the editor that mention "every entity" actually meant "all declarations and macro definitions". `std::views` should be a freestanding entity.
> 
> That'd also help clarify [#5713 (comment)](https://github.com/cplusplus/draft/pull/5713#discussion_r939710891). As per the literal instructions, class members of `allocator_arg_t` and more are appended `// freestanding`, but not those of `allocation_result`.

There are not handled by the LWG issue, though.
