### ISSUE TITLE
Why value_type for ostream_iterator is void?

### ISSUE THREAD

**Issue by tshev** [cplusplus/draft#721] opened 2016-05-07 10:53 UTC

**Comment by AlisdairM** [comment] 2016-05-10 01:01
It is a common convention for all output iterators (that are not also input iterators) to have 'void' for all their typedefs other than the iterator category.  If you think there is an issue here, it should be filed with the Library Working Group chair, as it is distinctly more than editorial - but I think the standard is exactly as intended here.

**Comment by jwakely** [comment] 2016-05-10 09:44
The only value operation to perform when dereferencing an iterator with category `output_iterator` is to assign to it, so a void value category discourages people from trying to do:

    iterator_traits<ostream_iterator<int>>::value_type = *ostr_iter;

Of course with `auto` you don't need to know the value type, but that doesn't mean that a non-void value type would be useful.

As Alisdair says, this is not an editorial issue, so does not belong here.

**Closed by jwakely** 2016-05-10 09:44 UTC
