### ISSUE TITLE
stop using teletype font for `constexpr` function

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#559] opened 2015-11-04 22:00 UTC
The term "constexpr function" is currently formatted as "`constexpr` function". This is misleading, since such functions need not use the `constexpr` specifier. Instead, we should only use the teletype font when referring to the keyword, matching how we treat the terms "inline function" and "function declared with the `inline` specifier".

**Comment by sigfpe** [comment] 2015-11-04 23:11
Makes sense.-------- Original message --------From: Richard Smith <notifications@github.com> Date: 11/4/2015  2:00 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: [draft] stop using teletype font for `constexpr` function (#559) 
The term "constexpr function" is currently formatted as "constexpr function". This is misleading, since such functions need not use the constexpr specifier. Instead, we should only use the teletype font when referring to the keyword, matching how we treat the terms "inline function" and "function declared with the inline specifier".

**Comment by tkoeppe** [comment] 2015-11-14 04:29
What's the desired replacement? Just "constexpr function" without typographic distinctions? Or a real term, like "constant-expression function"?

**Comment by jensmaurer** [comment] 2016-11-29 22:51
Duplicate of #825.

**Closed by jensmaurer** 2016-11-29 22:51 UTC
Labels: decision-required
