### ISSUE TITLE
inconsistently including or omitting comma between "// x.y.z" and rest of comment in synopses

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#403] opened 2014-11-15 00:32 UTC
See for instance 20.8.1.2

>  // 20.8.1.2.4, observers
>  // 20.8.1.2.5 modifiers

... but this inconsistency occurs in lots of places. We should pick one style and stick to it.

**Comment by jensmaurer** [comment] 2016-11-13 15:54
So, which one do you pick?

**Comment by tkoeppe** [comment] 2016-11-13 16:11
I'd prefer the style

    // 1.2.3, description:

I believe that's a widely used style in the library.

**Comment by jensmaurer** [comment] 2016-11-13 19:43
Richard?

**Comment by jensmaurer** [comment] 2016-11-23 14:56
Duplicate of #802.

**Closed by jensmaurer** 2016-11-23 14:56 UTC
Labels: decision-required
