### ISSUE TITLE
[tuple.helper, pair.astuple, array.tuple] Unconventional description of `tuple_element`

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2476] opened 2018-11-16 02:31 UTC
These use the _Requires:_ element which, according to [[structure.specifications]](https://wg21.link/structure.specifications), are for describing function semantics. They also use unconventional _Type:_ and _Value:_ elements.

`array`'s description can be done following the conventions:
```C++
template<size_t I, class T, size_t N>
  struct tuple_element<I, array<T, N>> {
    using type = T;
  };
```
`I < N` shall be `true`.

As they are, there is no conventional space for the description of the `type` member of the partial specializations for `tuple` and `pair`. `pair`'s could be elevated from english wording to code, as in `using type = conditional_t<I == 0, T1, T2>;`.

See https://wg21.link/tuple.helper, https://wg21.link/pair.astuple and https://wg21.link/array.tuple.
https://github.com/cplusplus/draft/blob/6a4eb3226408aa8da4e06f569c725bd75b66976e/source/utilities.tex#L1792-L1810
https://github.com/cplusplus/draft/blob/6a4eb3226408aa8da4e06f569c725bd75b66976e/source/utilities.tex#L885-L895
https://github.com/cplusplus/draft/blob/6a4eb3226408aa8da4e06f569c725bd75b66976e/source/containers.tex#L3400-L3411

**Comment by johelegp** [comment] 2018-11-22 23:59
I missed that these definitions are not enclosed in a namespace. Which is fine, since they are not meant to be instantiated as objects. But I still need to enclose them when documenting my own partial specializations depending on my program-defined types.

**Comment by johelegp** [comment] 2018-12-14 02:09
[`tuple_size`](http://eel.is/c++draft/tuple.helper#1) similarly uses a _Remarks:_ element.

**Comment by johelegp** [comment] 2019-03-27 22:37
https://wg21.link/LWG3193 generalizes this and other linked issues.

**Comment by jensmaurer** [comment] 2019-05-03 20:45
Duplicate of #2786.

**Closed by jensmaurer** 2019-05-03 20:45 UTC
