### ISSUE TITLE
[cstdint.syn] should list the macros it defines

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#1276] opened 2016-12-20 21:37 UTC
All other C header synopses, such as `[cfloat.syn]` just above, now list every macro they define on its own line, but `[cstdint.syn]` instead describes them in prose using unique pattern-matching language.  Should it be made as explicit as the other C header synopses?

**Comment by jensmaurer** [comment] 2016-12-20 22:59
See also pull request #843.

**Comment by jensmaurer** [comment] 2017-03-02 08:24
Duplicate of #843.

**Closed by jensmaurer** 2017-03-02 08:24 UTC
Labels: decision-required
