### ISSUE TITLE
Remarks: vs. Remark: and Postconditions: vs. Postcondition: in library

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#529] opened 2015-07-25 02:05 UTC
[structure.specifications] defines only _Remarks:_ and _Postconditions:_ elements, but the singular form _Remark:_ and _Postcondition:_ are also used throughout the library. (_Effect:_, OTOH, is only used in two lines in Table 28, the allocator requirements table.) This should be cleaned up.

**Comment by jensmaurer** [comment] 2016-11-13 15:46
Duplicate of #282.

**Closed by jensmaurer** 2016-11-13 15:46 UTC
Labels: lwg
