### ISSUE TITLE
"constexpr constructor" and "constexpr function" are defined terms and should not be formatted in code font

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#825] opened 2016-07-12 19:04 UTC
Some of the references to the defined terms "constexpr constructor" and "constexpr function" incorrectly use code font for the "constexpr" keyword. (We probably make this mistake for some other terms that include keywords, too.)

**Comment by jwakely** [comment] 2016-07-12 19:14
I wondered about this while applying the recent motions and followed the lead of [expr.const] which uses code font consistently. Getting it right there would set a good example :)

**Comment by jlaire** [comment] 2016-11-29 16:21
This seems to be a duplicate of https://github.com/cplusplus/draft/issues/559 (which is tagged "decision-required).

**Comment by tkoeppe** [comment] 2016-11-29 16:23
@jensmaurer: Could you please have a look at both issues?

**Comment by jensmaurer** [comment] 2016-11-29 22:52
I've closed #559 as a duplicate.

**Closed** 2016-11-30 10:29 UTC
